// Code generated by go run gob_gen.go; DO NOT EDIT.

package blueprint

import (
	"bytes"
	"fmt"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
	"reflect"
	"unsafe"
)

// begin of context.go
func init() {
	globResultCacheGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(globResultCache) })
	stringHashGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(stringHash) })
	VariationGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(Variation) })
}

func (r globResultCache) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Pattern); err != nil {
		return err
	}

	if r.Excludes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Excludes)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Excludes); val1++ {
			if err = gobtools.EncodeString(buf, r.Excludes[val1]); err != nil {
				return err
			}
		}
	}

	for val2 := 0; val2 < len(r.Result); val2++ {
		if err = gobtools.EncodeUint64(buf, r.Result[val2]); err != nil {
			return err
		}
	}
	return err
}

func (r globResultCache) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.globResultCache")
	hasher.WriteInt(3)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Pattern)
	hasher.WriteString(":.[]string")
	hasher.WriteInt(len(r.Excludes))
	for val1 := 0; val1 < len(r.Excludes); val1++ {
		hasher.WriteString(":.string")
		hasher.WriteString(r.Excludes[val1])
	}
	hasher.WriteString(":blueprint.proptools.Hash")
	hasher.WriteString(":.[1]uint64")
	hasher.WriteInt(len(r.Result))
	for val2 := 0; val2 < len(r.Result); val2++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.Result[val2]))
	}
	return nil
}

func (r *globResultCache) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Pattern)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Excludes = make([]string, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			err = gobtools.DecodeString(buf, &r.Excludes[val4])
			if err != nil {
				return err
			}
		}
	}

	for val8 := 0; val8 < len(r.Result); val8++ {
		err = gobtools.DecodeUint64(buf, &r.Result[val8])
		if err != nil {
			return err
		}
	}

	return err
}

var globResultCacheGobRegId int16

func (r globResultCache) GetTypeId() int16 {
	return globResultCacheGobRegId
}

func (r stringHash) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.string); err != nil {
		return err
	}
	return err
}

func (r stringHash) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.stringHash")
	hasher.WriteInt(1)
	hasher.WriteString(":.string")
	hasher.WriteString(r.string)
	return nil
}

func (r *stringHash) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.string)
	if err != nil {
		return err
	}

	return err
}

var stringHashGobRegId int16

func (r stringHash) GetTypeId() int16 {
	return stringHashGobRegId
}

func (r Variation) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Mutator); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Variation); err != nil {
		return err
	}
	return err
}

func (r Variation) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.Variation")
	hasher.WriteInt(2)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Mutator)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Variation)
	return nil
}

func (r *Variation) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Mutator)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Variation)
	if err != nil {
		return err
	}

	return err
}

var VariationGobRegId int16

func (r Variation) GetTypeId() int16 {
	return VariationGobRegId
}

// end of context.go

// begin of incremental.go
func init() {
	DataCacheKeyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(DataCacheKey) })
	CachedProviderGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CachedProvider) })
	ProviderHashGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProviderHash) })
	ModuleActionCachedDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleActionCachedData) })
	MutatorModuleStateCachedDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(MutatorModuleStateCachedData) })
	SourceModuleDeclarationGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SourceModuleDeclaration) })
	SourceDeclarationFileIndexGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SourceDeclarationFileIndex) })
	SourceModuleDeclarationFileSnapshotGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SourceModuleDeclarationFileSnapshot) })
	SingletonActionCachedDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SingletonActionCachedData) })
	ModuleProviderDependencyBitsetGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleProviderDependencyBitset) })
	SingletonProviderDependencyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SingletonProviderDependency) })
	OrderOnlyStringsCacheGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(OrderOnlyStringsCache) })
}

func (r DataCacheKey) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Id); err != nil {
		return err
	}
	return err
}

func (r DataCacheKey) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.DataCacheKey")
	hasher.WriteInt(1)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Id)
	return nil
}

func (r *DataCacheKey) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Id)
	if err != nil {
		return err
	}

	return err
}

var DataCacheKeyGobRegId int16

func (r DataCacheKey) GetTypeId() int16 {
	return DataCacheKeyGobRegId
}

func (r CachedProvider) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.Id == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.Id).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Value); err != nil {
		return err
	}
	return err
}

func (r CachedProvider) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.CachedProvider")
	hasher.WriteInt(2)
	hasher.WriteString(":.*providerKey")
	val1 := r.Id == nil
	if val1 {
		hasher.WriteByte(0)
	} else {
		val2 := func(hasher *proptools.Hasher) error {
			if err := (*r.Id).CustomHash(hasher); err != nil {
				return err
			}
			return nil
		}
		if err := proptools.HashReference(hasher, uintptr(unsafe.Pointer(r.Id)), val2); err != nil {
			return err
		}
	}
	hasher.WriteString(":.any")
	val3 := r.Value == nil
	if val3 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.Value); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val4 := r.Value == nil
				if val4 {
					hasher.WriteByte(0)
				} else {
					val5 := func(hasher *proptools.Hasher) error { return r.Value.(proptools.CustomHash).CustomHash(hasher) }
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val5); err != nil {
						return err
					}
				}
			}
		} else {
			r.Value.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	return nil
}

func (r *CachedProvider) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 providerKey
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.Id = &val1
	}

	if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val5 == nil {
		r.Value = nil
	} else {
		r.Value = val5
	}

	return err
}

var CachedProviderGobRegId int16

func (r CachedProvider) GetTypeId() int16 {
	return CachedProviderGobRegId
}

func (r ProviderHash) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.Id == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.Id).Encode(ctx, buf); err != nil {
			return err
		}
	}

	for val2 := 0; val2 < len(r.Hash); val2++ {
		if err = gobtools.EncodeUint64(buf, r.Hash[val2]); err != nil {
			return err
		}
	}
	return err
}

func (r ProviderHash) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.ProviderHash")
	hasher.WriteInt(2)
	hasher.WriteString(":.*providerKey")
	val1 := r.Id == nil
	if val1 {
		hasher.WriteByte(0)
	} else {
		val2 := func(hasher *proptools.Hasher) error {
			if err := (*r.Id).CustomHash(hasher); err != nil {
				return err
			}
			return nil
		}
		if err := proptools.HashReference(hasher, uintptr(unsafe.Pointer(r.Id)), val2); err != nil {
			return err
		}
	}
	hasher.WriteString(":blueprint.proptools.Hash")
	hasher.WriteString(":.[1]uint64")
	hasher.WriteInt(len(r.Hash))
	for val3 := 0; val3 < len(r.Hash); val3++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.Hash[val3]))
	}
	return nil
}

func (r *ProviderHash) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 providerKey
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.Id = &val1
	}

	for val6 := 0; val6 < len(r.Hash); val6++ {
		err = gobtools.DecodeUint64(buf, &r.Hash[val6])
		if err != nil {
			return err
		}
	}

	return err
}

var ProviderHashGobRegId int16

func (r ProviderHash) GetTypeId() int16 {
	return ProviderHashGobRegId
}

func (r ModuleActionCachedData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	for val1 := 0; val1 < len(r.InputHash); val1++ {
		if err = gobtools.EncodeUint64(buf, r.InputHash[val1]); err != nil {
			return err
		}
	}

	if r.ProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ProviderHashes)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.ProviderHashes); val2++ {
			if err = r.ProviderHashes[val2].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.OrderOnlyStrings == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.OrderOnlyStrings)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.OrderOnlyStrings); val3++ {
			if err = gobtools.EncodeString(buf, r.OrderOnlyStrings[val3]); err != nil {
				return err
			}
		}
	}

	if r.GlobCache == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GlobCache)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.GlobCache); val4++ {
			if err = r.GlobCache[val4].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r ModuleActionCachedData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.ModuleActionCachedData")
	hasher.WriteInt(4)
	hasher.WriteString(":blueprint.proptools.Hash")
	hasher.WriteString(":.[1]uint64")
	hasher.WriteInt(len(r.InputHash))
	for val1 := 0; val1 < len(r.InputHash); val1++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.InputHash[val1]))
	}
	hasher.WriteString(":.[]ProviderHash")
	hasher.WriteInt(len(r.ProviderHashes))
	for val2 := 0; val2 < len(r.ProviderHashes); val2++ {
		if err := r.ProviderHashes[val2].CustomHash(hasher); err != nil {
			return err
		}
	}
	hasher.WriteString(":.[]string")
	hasher.WriteInt(len(r.OrderOnlyStrings))
	for val3 := 0; val3 < len(r.OrderOnlyStrings); val3++ {
		hasher.WriteString(":.string")
		hasher.WriteString(r.OrderOnlyStrings[val3])
	}
	hasher.WriteString(":.[]globResultCache")
	hasher.WriteInt(len(r.GlobCache))
	for val4 := 0; val4 < len(r.GlobCache); val4++ {
		if err := r.GlobCache[val4].CustomHash(hasher); err != nil {
			return err
		}
	}
	return nil
}

func (r *ModuleActionCachedData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	for val3 := 0; val3 < len(r.InputHash); val3++ {
		err = gobtools.DecodeUint64(buf, &r.InputHash[val3])
		if err != nil {
			return err
		}
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.ProviderHashes = make([]ProviderHash, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			if err = r.ProviderHashes[val7].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val10 int
	err = gobtools.DecodeInt(buf, &val10)
	if err != nil {
		return err
	}
	if val10 != -1 {
		r.OrderOnlyStrings = make([]string, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			err = gobtools.DecodeString(buf, &r.OrderOnlyStrings[val11])
			if err != nil {
				return err
			}
		}
	}

	var val14 int
	err = gobtools.DecodeInt(buf, &val14)
	if err != nil {
		return err
	}
	if val14 != -1 {
		r.GlobCache = make([]globResultCache, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			if err = r.GlobCache[val15].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var ModuleActionCachedDataGobRegId int16

func (r ModuleActionCachedData) GetTypeId() int16 {
	return ModuleActionCachedDataGobRegId
}

func (r MutatorModuleStateCachedData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.Version); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Valid); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.State); err != nil {
		return err
	}
	return err
}

func (r MutatorModuleStateCachedData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.MutatorModuleStateCachedData")
	hasher.WriteInt(3)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.Version))
	hasher.WriteString(":.bool")
	if r.Valid {
		hasher.WriteByte(1)
	} else {
		hasher.WriteByte(0)
	}
	hasher.WriteString(":.string")
	hasher.WriteString(r.State)
	return nil
}

func (r *MutatorModuleStateCachedData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.Version)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Valid)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.State)
	if err != nil {
		return err
	}

	return err
}

var MutatorModuleStateCachedDataGobRegId int16

func (r MutatorModuleStateCachedData) GetTypeId() int16 {
	return MutatorModuleStateCachedDataGobRegId
}

func (r SourceModuleDeclaration) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Key); err != nil {
		return err
	}

	for val1 := 0; val1 < len(r.PropertiesHash); val1++ {
		if err = gobtools.EncodeUint64(buf, r.PropertiesHash[val1]); err != nil {
			return err
		}
	}

	if r.ModuleCacheKeys == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ModuleCacheKeys)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.ModuleCacheKeys); val2++ {
			if err = gobtools.EncodeString(buf, r.ModuleCacheKeys[val2]); err != nil {
				return err
			}
		}
	}

	if r.DependentDeclarations == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DependentDeclarations)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.DependentDeclarations); val3++ {
			if err = gobtools.EncodeString(buf, r.DependentDeclarations[val3]); err != nil {
				return err
			}
		}
	}

	if r.GlobCache == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GlobCache)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.GlobCache); val4++ {
			if err = r.GlobCache[val4].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r SourceModuleDeclaration) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.SourceModuleDeclaration")
	hasher.WriteInt(5)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Key)
	hasher.WriteString(":blueprint.proptools.Hash")
	hasher.WriteString(":.[1]uint64")
	hasher.WriteInt(len(r.PropertiesHash))
	for val1 := 0; val1 < len(r.PropertiesHash); val1++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.PropertiesHash[val1]))
	}
	hasher.WriteString(":.[]string")
	hasher.WriteInt(len(r.ModuleCacheKeys))
	for val2 := 0; val2 < len(r.ModuleCacheKeys); val2++ {
		hasher.WriteString(":.string")
		hasher.WriteString(r.ModuleCacheKeys[val2])
	}
	hasher.WriteString(":.[]string")
	hasher.WriteInt(len(r.DependentDeclarations))
	for val3 := 0; val3 < len(r.DependentDeclarations); val3++ {
		hasher.WriteString(":.string")
		hasher.WriteString(r.DependentDeclarations[val3])
	}
	hasher.WriteString(":.[]globResultCache")
	hasher.WriteInt(len(r.GlobCache))
	for val4 := 0; val4 < len(r.GlobCache); val4++ {
		if err := r.GlobCache[val4].CustomHash(hasher); err != nil {
			return err
		}
	}
	return nil
}

func (r *SourceModuleDeclaration) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Key)
	if err != nil {
		return err
	}

	for val4 := 0; val4 < len(r.PropertiesHash); val4++ {
		err = gobtools.DecodeUint64(buf, &r.PropertiesHash[val4])
		if err != nil {
			return err
		}
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.ModuleCacheKeys = make([]string, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			err = gobtools.DecodeString(buf, &r.ModuleCacheKeys[val8])
			if err != nil {
				return err
			}
		}
	}

	var val11 int
	err = gobtools.DecodeInt(buf, &val11)
	if err != nil {
		return err
	}
	if val11 != -1 {
		r.DependentDeclarations = make([]string, val11)
		for val12 := 0; val12 < int(val11); val12++ {
			err = gobtools.DecodeString(buf, &r.DependentDeclarations[val12])
			if err != nil {
				return err
			}
		}
	}

	var val15 int
	err = gobtools.DecodeInt(buf, &val15)
	if err != nil {
		return err
	}
	if val15 != -1 {
		r.GlobCache = make([]globResultCache, val15)
		for val16 := 0; val16 < int(val15); val16++ {
			if err = r.GlobCache[val16].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var SourceModuleDeclarationGobRegId int16

func (r SourceModuleDeclaration) GetTypeId() int16 {
	return SourceModuleDeclarationGobRegId
}

func (r SourceDeclarationFileIndex) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.Version); err != nil {
		return err
	}

	if r.Files == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Files)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Files); val1++ {
			if err = gobtools.EncodeString(buf, r.Files[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.GraphComplete); err != nil {
		return err
	}
	return err
}

func (r SourceDeclarationFileIndex) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.SourceDeclarationFileIndex")
	hasher.WriteInt(3)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.Version))
	hasher.WriteString(":.[]string")
	hasher.WriteInt(len(r.Files))
	for val1 := 0; val1 < len(r.Files); val1++ {
		hasher.WriteString(":.string")
		hasher.WriteString(r.Files[val1])
	}
	hasher.WriteString(":.bool")
	if r.GraphComplete {
		hasher.WriteByte(1)
	} else {
		hasher.WriteByte(0)
	}
	return nil
}

func (r *SourceDeclarationFileIndex) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.Version)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Files = make([]string, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			err = gobtools.DecodeString(buf, &r.Files[val4])
			if err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.GraphComplete)
	if err != nil {
		return err
	}

	return err
}

var SourceDeclarationFileIndexGobRegId int16

func (r SourceDeclarationFileIndex) GetTypeId() int16 {
	return SourceDeclarationFileIndexGobRegId
}

func (r SourceModuleDeclarationFileSnapshot) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.Version); err != nil {
		return err
	}

	if r.Modules == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Modules)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Modules); val1++ {
			if err = r.Modules[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r SourceModuleDeclarationFileSnapshot) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.SourceModuleDeclarationFileSnapshot")
	hasher.WriteInt(2)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.Version))
	hasher.WriteString(":.[]SourceModuleDeclaration")
	hasher.WriteInt(len(r.Modules))
	for val1 := 0; val1 < len(r.Modules); val1++ {
		if err := r.Modules[val1].CustomHash(hasher); err != nil {
			return err
		}
	}
	return nil
}

func (r *SourceModuleDeclarationFileSnapshot) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.Version)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Modules = make([]SourceModuleDeclaration, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if err = r.Modules[val4].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var SourceModuleDeclarationFileSnapshotGobRegId int16

func (r SourceModuleDeclarationFileSnapshot) GetTypeId() int16 {
	return SourceModuleDeclarationFileSnapshotGobRegId
}

func (r SingletonActionCachedData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.CacheVersion); err != nil {
		return err
	}

	if r.ProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ProviderHashes)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ProviderHashes); val1++ {
			if err = r.ProviderHashes[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.DependencyProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DependencyProviderHashes)); err != nil {
			return err
		}
		for val2, val3 := range r.DependencyProviderHashes {
			if err = gobtools.EncodeInt(buf, val2); err != nil {
				return err
			}
			for val4 := 0; val4 < len(val3); val4++ {
				if err = gobtools.EncodeUint64(buf, val3[val4]); err != nil {
					return err
				}
			}
		}
	}

	if r.ModuleDependencyBloom == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ModuleDependencyBloom)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.ModuleDependencyBloom); val5++ {
			if err = gobtools.EncodeUint64(buf, r.ModuleDependencyBloom[val5]); err != nil {
				return err
			}
		}
	}

	if r.ModuleProviderDependencyBitsets == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ModuleProviderDependencyBitsets)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.ModuleProviderDependencyBitsets); val6++ {
			if err = r.ModuleProviderDependencyBitsets[val6].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeString(buf, r.ModuleSetHash); err != nil {
		return err
	}

	if r.SingletonProviderDependencies == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SingletonProviderDependencies)); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.SingletonProviderDependencies); val7++ {
			if err = r.SingletonProviderDependencies[val7].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeString(buf, r.SingletonSetHash); err != nil {
		return err
	}

	if r.GlobCache == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GlobCache)); err != nil {
			return err
		}
		for val8 := 0; val8 < len(r.GlobCache); val8++ {
			if err = r.GlobCache[val8].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r SingletonActionCachedData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.SingletonActionCachedData")
	hasher.WriteInt(9)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.CacheVersion))
	hasher.WriteString(":.[]ProviderHash")
	hasher.WriteInt(len(r.ProviderHashes))
	for val1 := 0; val1 < len(r.ProviderHashes); val1++ {
		if err := r.ProviderHashes[val1].CustomHash(hasher); err != nil {
			return err
		}
	}
	hasher.WriteString(":.map[int]proptools.Hash")
	hasher.WriteInt(len(r.DependencyProviderHashes))
	val2 := make([]int, 0, len(r.DependencyProviderHashes))
	for val4 := range r.DependencyProviderHashes {
		val2 = append(val2, val4)
	}
	proptools.SortOrdered(val2)
	for _, val3 := range val2 {
		hasher.WriteString(":.int")
		hasher.WriteUint64(uint64(val3))
		hasher.WriteString(":blueprint.proptools.Hash")
		hasher.WriteString(":.[1]uint64")
		hasher.WriteInt(len(r.DependencyProviderHashes[val3]))
		for val5 := 0; val5 < len(r.DependencyProviderHashes[val3]); val5++ {
			hasher.WriteString(":.uint64")
			hasher.WriteUint64(uint64(r.DependencyProviderHashes[val3][val5]))
		}
	}
	hasher.WriteString(":.[]uint64")
	hasher.WriteInt(len(r.ModuleDependencyBloom))
	for val6 := 0; val6 < len(r.ModuleDependencyBloom); val6++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.ModuleDependencyBloom[val6]))
	}
	hasher.WriteString(":.[]ModuleProviderDependencyBitset")
	hasher.WriteInt(len(r.ModuleProviderDependencyBitsets))
	for val7 := 0; val7 < len(r.ModuleProviderDependencyBitsets); val7++ {
		if err := r.ModuleProviderDependencyBitsets[val7].CustomHash(hasher); err != nil {
			return err
		}
	}
	hasher.WriteString(":.string")
	hasher.WriteString(r.ModuleSetHash)
	hasher.WriteString(":.[]SingletonProviderDependency")
	hasher.WriteInt(len(r.SingletonProviderDependencies))
	for val8 := 0; val8 < len(r.SingletonProviderDependencies); val8++ {
		if err := r.SingletonProviderDependencies[val8].CustomHash(hasher); err != nil {
			return err
		}
	}
	hasher.WriteString(":.string")
	hasher.WriteString(r.SingletonSetHash)
	hasher.WriteString(":.[]globResultCache")
	hasher.WriteInt(len(r.GlobCache))
	for val9 := 0; val9 < len(r.GlobCache); val9++ {
		if err := r.GlobCache[val9].CustomHash(hasher); err != nil {
			return err
		}
	}
	return nil
}

func (r *SingletonActionCachedData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.CacheVersion)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.ProviderHashes = make([]ProviderHash, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if err = r.ProviderHashes[val4].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.DependencyProviderHashes = make(map[int]proptools.Hash, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			var val8 int
			var val9 proptools.Hash
			err = gobtools.DecodeInt(buf, &val8)
			if err != nil {
				return err
			}
			for val13 := 0; val13 < len(val9); val13++ {
				err = gobtools.DecodeUint64(buf, &val9[val13])
				if err != nil {
					return err
				}
			}
			r.DependencyProviderHashes[val8] = val9
		}
	}

	var val16 int
	err = gobtools.DecodeInt(buf, &val16)
	if err != nil {
		return err
	}
	if val16 != -1 {
		r.ModuleDependencyBloom = make([]uint64, val16)
		for val17 := 0; val17 < int(val16); val17++ {
			err = gobtools.DecodeUint64(buf, &r.ModuleDependencyBloom[val17])
			if err != nil {
				return err
			}
		}
	}

	var val20 int
	err = gobtools.DecodeInt(buf, &val20)
	if err != nil {
		return err
	}
	if val20 != -1 {
		r.ModuleProviderDependencyBitsets = make([]ModuleProviderDependencyBitset, val20)
		for val21 := 0; val21 < int(val20); val21++ {
			if err = r.ModuleProviderDependencyBitsets[val21].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeString(buf, &r.ModuleSetHash)
	if err != nil {
		return err
	}

	var val25 int
	err = gobtools.DecodeInt(buf, &val25)
	if err != nil {
		return err
	}
	if val25 != -1 {
		r.SingletonProviderDependencies = make([]SingletonProviderDependency, val25)
		for val26 := 0; val26 < int(val25); val26++ {
			if err = r.SingletonProviderDependencies[val26].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeString(buf, &r.SingletonSetHash)
	if err != nil {
		return err
	}

	var val30 int
	err = gobtools.DecodeInt(buf, &val30)
	if err != nil {
		return err
	}
	if val30 != -1 {
		r.GlobCache = make([]globResultCache, val30)
		for val31 := 0; val31 < int(val30); val31++ {
			if err = r.GlobCache[val31].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var SingletonActionCachedDataGobRegId int16

func (r SingletonActionCachedData) GetTypeId() int16 {
	return SingletonActionCachedDataGobRegId
}

func (r ModuleProviderDependencyBitset) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.ProviderId); err != nil {
		return err
	}

	if r.Modules == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Modules)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Modules); val1++ {
			if err = gobtools.EncodeUint64(buf, r.Modules[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r ModuleProviderDependencyBitset) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.ModuleProviderDependencyBitset")
	hasher.WriteInt(2)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.ProviderId))
	hasher.WriteString(":.[]uint64")
	hasher.WriteInt(len(r.Modules))
	for val1 := 0; val1 < len(r.Modules); val1++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.Modules[val1]))
	}
	return nil
}

func (r *ModuleProviderDependencyBitset) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.ProviderId)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Modules = make([]uint64, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			err = gobtools.DecodeUint64(buf, &r.Modules[val4])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var ModuleProviderDependencyBitsetGobRegId int16

func (r ModuleProviderDependencyBitset) GetTypeId() int16 {
	return ModuleProviderDependencyBitsetGobRegId
}

func (r SingletonProviderDependency) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.SingletonName); err != nil {
		return err
	}

	if err = gobtools.EncodeInt(buf, r.ProviderId); err != nil {
		return err
	}

	for val1 := 0; val1 < len(r.Hash); val1++ {
		if err = gobtools.EncodeUint64(buf, r.Hash[val1]); err != nil {
			return err
		}
	}
	return err
}

func (r SingletonProviderDependency) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.SingletonProviderDependency")
	hasher.WriteInt(3)
	hasher.WriteString(":.string")
	hasher.WriteString(r.SingletonName)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.ProviderId))
	hasher.WriteString(":blueprint.proptools.Hash")
	hasher.WriteString(":.[1]uint64")
	hasher.WriteInt(len(r.Hash))
	for val1 := 0; val1 < len(r.Hash); val1++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.Hash[val1]))
	}
	return nil
}

func (r *SingletonProviderDependency) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.SingletonName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeInt(buf, &r.ProviderId)
	if err != nil {
		return err
	}

	for val5 := 0; val5 < len(r.Hash); val5++ {
		err = gobtools.DecodeUint64(buf, &r.Hash[val5])
		if err != nil {
			return err
		}
	}

	return err
}

var SingletonProviderDependencyGobRegId int16

func (r SingletonProviderDependency) GetTypeId() int16 {
	return SingletonProviderDependencyGobRegId
}

func (r OrderOnlyStringsCache) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1, val2 := range r {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeString(buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r OrderOnlyStringsCache) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":.map[string][]string")
	hasher.WriteInt(len(r))
	val1 := make([]string, 0, len(r))
	for val3 := range r {
		val1 = append(val1, val3)
	}
	proptools.SortOrdered(val1)
	for _, val2 := range val1 {
		hasher.WriteString(":.string")
		hasher.WriteString(val2)
		hasher.WriteString(":.[]string")
		hasher.WriteInt(len(r[val2]))
		for val4 := 0; val4 < len(r[val2]); val4++ {
			hasher.WriteString(":.string")
			hasher.WriteString(r[val2][val4])
		}
	}
	return nil
}

func (r *OrderOnlyStringsCache) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		(*r) = make(map[string][]string, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 []string
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			if val7 != -1 {
				val4 = make([]string, val7)
				for val8 := 0; val8 < int(val7); val8++ {
					err = gobtools.DecodeString(buf, &val4[val8])
					if err != nil {
						return err
					}
				}
			}
			(*r)[val3] = val4
		}
	}

	return err
}

var OrderOnlyStringsCacheGobRegId int16

func (r OrderOnlyStringsCache) GetTypeId() int16 {
	return OrderOnlyStringsCacheGobRegId
}

// end of incremental.go

// begin of incremental_module.go
func init() {
	ModuleBuildActionCacheInputGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleBuildActionCacheInput) })
	hashListGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(hashList) })
	stringListGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(stringList) })
}

func (r ModuleBuildActionCacheInput) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	for val1 := 0; val1 < len(r.PropertiesHash); val1++ {
		if err = gobtools.EncodeUint64(buf, r.PropertiesHash[val1]); err != nil {
			return err
		}
	}

	if r.DepProviderHashes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DepProviderHashes)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.DepProviderHashes); val2++ {
			for val3 := 0; val3 < len(r.DepProviderHashes[val2]); val3++ {
				if err = gobtools.EncodeUint64(buf, r.DepProviderHashes[val2][val3]); err != nil {
					return err
				}
			}
		}
	}
	return err
}

func (r ModuleBuildActionCacheInput) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.ModuleBuildActionCacheInput")
	hasher.WriteInt(2)
	hasher.WriteString(":blueprint.proptools.Hash")
	hasher.WriteString(":.[1]uint64")
	hasher.WriteInt(len(r.PropertiesHash))
	for val1 := 0; val1 < len(r.PropertiesHash); val1++ {
		hasher.WriteString(":.uint64")
		hasher.WriteUint64(uint64(r.PropertiesHash[val1]))
	}
	hasher.WriteString(":.[]proptools.Hash")
	hasher.WriteInt(len(r.DepProviderHashes))
	for val2 := 0; val2 < len(r.DepProviderHashes); val2++ {
		hasher.WriteString(":blueprint.proptools.Hash")
		hasher.WriteString(":.[1]uint64")
		hasher.WriteInt(len(r.DepProviderHashes[val2]))
		for val3 := 0; val3 < len(r.DepProviderHashes[val2]); val3++ {
			hasher.WriteString(":.uint64")
			hasher.WriteUint64(uint64(r.DepProviderHashes[val2][val3]))
		}
	}
	return nil
}

func (r *ModuleBuildActionCacheInput) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	for val3 := 0; val3 < len(r.PropertiesHash); val3++ {
		err = gobtools.DecodeUint64(buf, &r.PropertiesHash[val3])
		if err != nil {
			return err
		}
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.DepProviderHashes = make([]proptools.Hash, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			for val10 := 0; val10 < len(r.DepProviderHashes[val7]); val10++ {
				err = gobtools.DecodeUint64(buf, &r.DepProviderHashes[val7][val10])
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

var ModuleBuildActionCacheInputGobRegId int16

func (r ModuleBuildActionCacheInput) GetTypeId() int16 {
	return ModuleBuildActionCacheInputGobRegId
}

func (r hashList) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r); val1++ {
			for val2 := 0; val2 < len(r[val1]); val2++ {
				if err = gobtools.EncodeUint64(buf, r[val1][val2]); err != nil {
					return err
				}
			}
		}
	}
	return err
}

func (r hashList) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":.[]proptools.Hash")
	hasher.WriteInt(len(r))
	for val1 := 0; val1 < len(r); val1++ {
		hasher.WriteString(":blueprint.proptools.Hash")
		hasher.WriteString(":.[1]uint64")
		hasher.WriteInt(len(r[val1]))
		for val2 := 0; val2 < len(r[val1]); val2++ {
			hasher.WriteString(":.uint64")
			hasher.WriteUint64(uint64(r[val1][val2]))
		}
	}
	return nil
}

func (r *hashList) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		(*r) = make([]proptools.Hash, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			for val6 := 0; val6 < len((*r)[val3]); val6++ {
				err = gobtools.DecodeUint64(buf, &(*r)[val3][val6])
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

var hashListGobRegId int16

func (r hashList) GetTypeId() int16 {
	return hashListGobRegId
}

func (r stringList) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r); val1++ {
			if err = gobtools.EncodeString(buf, r[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r stringList) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":.[]string")
	hasher.WriteInt(len(r))
	for val1 := 0; val1 < len(r); val1++ {
		hasher.WriteString(":.string")
		hasher.WriteString(r[val1])
	}
	return nil
}

func (r *stringList) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		(*r) = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &(*r)[val3])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var stringListGobRegId int16

func (r stringList) GetTypeId() int16 {
	return stringListGobRegId
}

// end of incremental_module.go

// begin of provider.go
func init() {
	providerKeyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(providerKey) })
}

func (r providerKey) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, r.id); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.typ); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.mutator); err != nil {
		return err
	}
	return err
}

func (r providerKey) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":blueprint.providerKey")
	hasher.WriteInt(3)
	hasher.WriteString(":.int")
	hasher.WriteUint64(uint64(r.id))
	hasher.WriteString(":.string")
	hasher.WriteString(r.typ)
	hasher.WriteString(":.string")
	hasher.WriteString(r.mutator)
	return nil
}

func (r *providerKey) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeInt(buf, &r.id)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.typ)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.mutator)
	if err != nil {
		return err
	}

	return err
}

var providerKeyGobRegId int16

func (r providerKey) GetTypeId() int16 {
	return providerKeyGobRegId
}

// end of provider.go
