// Copyright 2025 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pathtools

import (
	"errors"
	"io"
	"os"
)

const OutFilePermissions = 0666

// OpenWithTruncateOnClose opens a file for writing, but does not use O_TRUNC so that the existing filesystem
// blocks are not deallocated.  The file will be truncated to the number of bytes written on close.
func OpenWithTruncateOnClose(fs FileSystem, path string) (io.WriteCloser, error) {
	f, err := fs.OpenFile(path, os.O_WRONLY|os.O_CREATE, OutFilePermissions)
	if err != nil {
		return nil, err
	}
	return &truncateOnCloseWrapper{
		w: f,
	}, nil
}

// ContentComparisonWriteCloser reports whether sequential output changed the
// file contents and how many bytes were written to the file.
type ContentComparisonWriteCloser interface {
	io.WriteCloser
	ContentChanged() bool
	BytesWritten() int64
}

// OpenWithContentComparison opens a file for sequential writing and compares
// the generated bytes against the existing file. It does not open the file for
// writing unless the contents differ, avoiding large no-op rewrites while
// keeping memory use bounded.
func OpenWithContentComparison(fs FileSystem, path string) (ContentComparisonWriteCloser, error) {
	old, err := fs.Open(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	return &contentComparisonWriter{
		fs:        fs,
		path:      path,
		old:       old,
		oldExists: old != nil,
		compare:   make([]byte, 64*1024),
	}, nil
}

func (w *contentComparisonWriter) ContentChanged() bool {
	return w.writer != nil
}

func (w *contentComparisonWriter) BytesWritten() int64 {
	return w.written
}

type contentComparisonWriter struct {
	fs        FileSystem
	path      string
	old       ReaderAtSeekerCloser
	oldExists bool
	compare   []byte
	writer    WriteTruncateCloser
	matched   int64
	written   int64
	closed    bool
}

func (w *contentComparisonWriter) startWriting() error {
	if w.writer != nil {
		return nil
	}
	f, err := w.fs.OpenFile(w.path, os.O_WRONLY|os.O_CREATE, OutFilePermissions)
	if err != nil {
		return err
	}
	w.writer = f
	if w.matched > 0 {
		prefix := io.NewSectionReader(w.old, 0, w.matched)
		written, err := io.CopyN(w.writer, prefix, w.matched)
		w.written = written
		if err != nil {
			return err
		}
	}
	return nil
}

func (w *contentComparisonWriter) Write(p []byte) (int, error) {
	if w.closed {
		return 0, os.ErrClosed
	}
	if w.writer != nil {
		n, err := w.writer.Write(p)
		w.written += int64(n)
		return n, err
	}
	if !w.oldExists {
		if err := w.startWriting(); err != nil {
			return 0, err
		}
		n, err := w.writer.Write(p)
		w.written += int64(n)
		return n, err
	}

	callStart := w.matched
	for compared := 0; compared < len(p); {
		chunk := min(len(p)-compared, len(w.compare))
		n, err := w.old.ReadAt(w.compare[:chunk], w.matched)
		if err != nil && !errors.Is(err, io.EOF) {
			return compared, err
		}
		mismatch := -1
		for i := 0; i < n; i++ {
			if w.compare[i] != p[compared+i] {
				mismatch = i
				break
			}
		}
		if mismatch >= 0 {
			w.matched += int64(mismatch)
			if err := w.startWriting(); err != nil {
				return compared + mismatch, err
			}
			written, writeErr := w.writer.Write(p[compared+mismatch:])
			w.written += int64(written)
			return compared + mismatch + written, writeErr
		}
		w.matched += int64(n)
		compared += n
		if n < chunk {
			if n == 0 && err == nil {
				return compared, io.ErrNoProgress
			}
			if startErr := w.startWriting(); startErr != nil {
				return compared, startErr
			}
			written, writeErr := w.writer.Write(p[compared:])
			w.written += int64(written)
			return compared + written, writeErr
		}
		if n == 0 {
			return compared, io.ErrNoProgress
		}
	}
	if w.matched-callStart != int64(len(p)) {
		return int(w.matched - callStart), io.ErrNoProgress
	}
	return len(p), nil
}

func (w *contentComparisonWriter) Close() error {
	if w.closed {
		return os.ErrClosed
	}
	w.closed = true
	var writeErr error
	if w.writer == nil {
		if !w.oldExists {
			writeErr = w.startWriting()
		} else {
			var extra [1]byte
			n, err := w.old.ReadAt(extra[:], w.matched)
			if err != nil && !errors.Is(err, io.EOF) {
				writeErr = err
			} else if n > 0 {
				writeErr = w.startWriting()
			}
		}
	}
	var truncateErr error
	var writerCloseErr error
	if w.writer != nil {
		if writeErr == nil {
			truncateErr = w.writer.Truncate(w.written)
		}
		writerCloseErr = w.writer.Close()
	}
	var oldCloseErr error
	if w.old != nil {
		oldCloseErr = w.old.Close()
	}
	return errors.Join(writeErr, truncateErr, writerCloseErr, oldCloseErr)
}

type truncateOnCloseWrapper struct {
	w     WriteTruncateCloser
	count int
}

func (t *truncateOnCloseWrapper) Write(p []byte) (int, error) {
	n, err := t.w.Write(p)
	t.count += n
	return n, err
}

func (t *truncateOnCloseWrapper) Close() error {
	err := t.w.Truncate(int64(t.count))
	err2 := t.w.Close()
	return errors.Join(err, err2)
}
